'use client';

import { ChangeEvent, useRef, useState } from 'react';
type Status='合规'|'违规'|'无法判断'; type Risk='高风险'|'中风险'|'无风险'|'无法判断'; type Category='审查通过'|'需重拍'|'需整改'; type ReviewStage='待督导复核'|'已关闭'|'待补拍'|'待继续整改'|'高风险升级';
type Finding={item:string;status:Status;ruleId:string;ruleText:string;risk:Risk;evidence:string;recommendation:string;confidence:number;reason?:string};
type Record={id:string;store:string;image:string;finding:Finding;category:Category;reviewStage:ReviewStage;reshootRejects:number;archived?:boolean;sampled?:boolean;beforeImage?:string;afterImage?:string};
const rules=[['R-CTR-001','操作台'],['R-ING-001','原料'],['R-LAB-001','标签'],['R-BIN-001','垃圾桶'],['R-EMP-001','员工着装'],['R-CLN-001','清洁工具'],['R-EQP-001','器具与地面']] as const;
const stores=['上海静安嘉里中心店','上海徐汇日月光店','杭州湖滨银泰店'];
const categoryOf=(finding:Finding):Category=>finding.status==='合规'?'审查通过':finding.status==='无法判断'?'需重拍':'需整改';
function Pill({value}:{value:Status|Risk|Category}){const c=value==='违规'||value==='高风险'||value==='需整改'?'danger':value==='无法判断'||value==='需重拍'?'pending':'safe';return <span className={`pill ${c}`}>{value}</span>}
async function compressImage(file:File){if(typeof createImageBitmap==='undefined')return await new Promise<string>(resolve=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.readAsDataURL(file)});const bitmap=await createImageBitmap(file);const scale=Math.min(1,960/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.7)}

export default function Home(){
 const [role,setRole]=useState<'店长'|'督导'|null>(null),[store,setStore]=useState(stores[0]),[supervisorStore,setSupervisorStore]=useState(stores[0]),[item,setItem]=useState('垃圾桶'),[image,setImage]=useState(''),[data,setData]=useState<string|null>(null),[hasUpload,setHasUpload]=useState(false),[records,setRecords]=useState<Record[]>([]),[activeId,setActiveId]=useState<string|null>(null),[replaceId,setReplaceId]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showRules,setShowRules]=useState(false); const picker=useRef<HTMLInputElement>(null);
 const active=records.find(x=>x.id===activeId)||null; const scopeRecords=role==='督导'?records.filter(x=>x.store===supervisorStore):records.filter(x=>x.store===store); const supervisorActive=active?.store===supervisorStore?active:scopeRecords[0]||null; const passed=scopeRecords.filter(x=>x.category==='审查通过').length; const hasRisk=scopeRecords.some(x=>x.category!=='审查通过'); const categoryRecords=(category:Category)=>scopeRecords.filter(record=>record.category===category); const closed=scopeRecords.filter(x=>x.reviewStage==='已关闭'); const compliance=closed.length?Math.round(closed.filter(x=>x.category==='审查通过').length/closed.length*100):0; const historyCard=(record:Record)=><button key={record.id} className={`history-card ${activeId===record.id?'selected':''}`} onClick={()=>setActiveId(record.id)}><img src={record.image} alt={`${record.finding.item}检查记录`}/><div><Pill value={record.category}/><b>{record.finding.item}</b><small>{record.finding.confidence}% 置信度</small><em>{record.reviewStage}</em>{record.category!=='审查通过'&&<span className="reupload-link" onClick={e=>{e.stopPropagation();if(!busy)reupload(record)}}>{busy&&replaceId===record.id?'正在检查':'重新上传 →'}</span>}</div></button>;
 async function onFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setMessage('正在处理照片…');const optimized=await compressImage(file);setImage(optimized);setData(optimized);setHasUpload(true);e.target.value='';if(replaceId){await runInspection(optimized,replaceId);return;}setActiveId(null);setMessage('图片已就绪，请点击“开始检查”。');}
 async function runInspection(photo:string,replacingId:string|null){setBusy(true);setMessage('正在检查…');try{const res=await fetch('/api/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:photo,item,store})});const result=await res.json() as {error?:string;finding?:Finding};if(!res.ok||!result.finding)throw new Error(result.error||'检查暂时不可用');const previous=records.find(x=>x.id===replacingId);const isRectification=previous?.category==='需整改';const record:Record={id:replacingId||`rec-${Date.now()}`,store:previous?.store||store,image:photo,finding:result.finding,category:categoryOf(result.finding),reviewStage:'待督导复核',reshootRejects:previous?.reshootRejects||0,...(isRectification?{beforeImage:previous.beforeImage||previous.image,afterImage:photo}:{})};setRecords(x=>replacingId?x.map(r=>r.id===replacingId?record:r):[...x,record]);setActiveId(record.id);setReplaceId(null);setData(null);setMessage(isRectification?'整改后照片已重新检查，已保留整改前后对比。':'检查完成，结果已保存到本次巡检记录。');}catch(e){setMessage(e instanceof Error?e.message:'检查失败，请稍后再试。');}finally{setBusy(false)}}
 async function inspect(){if(!data){setMessage('请先从相册上传或现场拍摄一张巡检照片。');return;}await runInspection(data,replaceId)}
 function reupload(record:Record){setItem(record.finding.item);setImage(record.image);setData(null);setReplaceId(record.id);setActiveId(record.id);setMessage(`${record.category}：请上传新的 ${record.finding.item} 照片，完成后点击“开始检查”。`);picker.current?.click()}
 function rectify(){if(active)reupload(active)} function updateReview(record:Record,patch:Partial<Record>,notice:string){setRecords(rows=>rows.map(row=>row.id===record.id?{...row,...patch}:row));setMessage(notice)} function archive(record:Record){updateReview(record,{reviewStage:'已关闭',archived:true,sampled:true},'督导已确认关闭并归档，已计入门店合规率和抽检样本。')} function rejectRephoto(record:Record){const count=record.reshootRejects+1;updateReview(record,{reshootRejects:count,reviewStage:count>=2?'高风险升级':'待补拍'},count>=2?'已超过补拍阈值，自动升级至区域负责人。':'已驳回补拍，请店长按原因重新拍摄。')} function rejectRectification(record:Record){updateReview(record,{reviewStage:'待继续整改'},'已驳回整改，请继续整改并提交新的证据。')} function escalate(record:Record){updateReview(record,{reviewStage:'高风险升级'},'高风险已升级：立即停售/隔离，已通知区域负责人，限时 2 小时复核。')}
 if(!role)return <main><header className="topbar"><div className="brand"><span className="brand-mark">茶</span><span>净巡 · 卫生巡检</span></div><span className="date-badge">2026.08.27</span></header><section className="hero role-hero"><p className="eyebrow">WELCOME TO JINGXUN</p><h1>开始今天的巡检</h1><p>请选择你的工作身份，进入对应的任务视图。</p></section><section className="identity-card"><p className="section-kicker">选择身份</p><button className="identity-option" onClick={()=>setRole('店长')}><span className="identity-icon">店</span><span><b>我是店长</b><small>拍照巡检、查看检查结论、提交整改</small></span><i>→</i></button><button className="identity-option" onClick={()=>setRole('督导')}><span className="identity-icon supervisor">督</span><span><b>我是督导</b><small>查看待复核任务、核对证据并关闭整改</small></span><i>→</i></button></section><section className="entry-note"><b>本次 Demo 支持</b><span>相册上传 · 现场拍摄 · 规则驱动分析 · 整改复核闭环</span></section><footer>系统仅依据已启用规则判定 · 证据不足时输出“无法判断”</footer></main>;
 return <main><header className="topbar"><div className="brand"><span className="brand-mark">茶</span><span>净巡 · 卫生巡检</span></div><button className="switch-role" onClick={()=>setRole(null)}>切换角色</button></header><section className="hero"><p className="eyebrow">TODAY · 2026.08.27</p><h1>今日巡检</h1><p>用清晰证据，让食品安全闭环更快发生。</p></section><div className="role-label">当前身份：<b>{role}</b>{role==='店长'?' · 请选择门店、检查项并上传巡检照片。':' · 请复核检查结论与整改证据。'}</div>
 <section className="dashboard-card progress-card"><div><p className="section-kicker">本日进度</p><strong>{passed} <small>/ 7 已通过</small></strong></div><div className="progress-track"><span style={{width:`${Math.max(8,passed/7*100)}%`}}/></div>{hasRisk?<span className="pill danger">有风险</span>:<Pill value={passed?'无风险':'无法判断'}/>}</section>
 {role==='店长'&&<section className="dashboard-card task-card inspection-zone"><div className="card-heading"><div><p className="section-kicker">发起巡检</p><h2>{store}</h2></div></div><label className="field-label">门店<select value={store} onChange={e=>setStore(e.target.value)}>{stores.map(x=><option key={x}>{x}</option>)}</select></label><label className="field-label">检查项<select value={item} onChange={e=>setItem(e.target.value)}>{rules.map(([,x])=><option key={x}>{x}</option>)}</select></label><div className={`upload-zone uploader-only ${hasUpload?'has-upload':''}`} style={hasUpload?{backgroundImage:`linear-gradient(rgba(48,31,23,.58),rgba(48,31,23,.58)),url("${image}")`}:undefined}><label className="upload-action"><input ref={picker} aria-label="从相册上传或现场拍摄巡检照片" type="file" accept="image/*" onChange={onFile}/><span>＋</span> 从相册上传 / 现场拍摄</label><p>{hasUpload?'照片已上传，可继续替换':'选择一张清晰、完整的检查区域照片'}</p></div><p className="photo-tip">图片模糊、过暗或关键区域未入镜时会要求补拍。</p><button className="primary-button" onClick={inspect} disabled={busy}>开始检查</button></section>}
 {role==='督导'&&<section className="dashboard-card inspection-zone supervisor-panel"><div className="card-heading"><div><p className="section-kicker">督导复核</p><h2>{supervisorActive?'门店巡检任务':'当前门店暂无记录'}</h2></div></div><label className="field-label">查看门店<select value={supervisorStore} onChange={e=>{const next=e.target.value;setSupervisorStore(next);setActiveId(records.find(row=>row.store===next)?.id||null)}}>{stores.map(x=><option key={x}>{x}</option>)}</select></label><div className="compliance-strip"><span>已归档合规率 <b>{compliance}%</b></span><span>抽检样本 <b>{closed.filter(x=>x.sampled).length}</b></span></div>{supervisorActive?<><div className="review-row"><span>检查建议</span><b>{supervisorActive.finding.status} · {supervisorActive.finding.confidence}% 置信度</b></div><div className="review-row"><span>当前处置</span><b>{supervisorActive.reviewStage}</b></div><p className="review-copy">{supervisorActive.finding.reason||supervisorActive.finding.evidence}</p>{supervisorActive.reviewStage==='高风险升级'?<div className="escalation-box"><b>已触发高风险处置</b><span>立即停售/隔离 · 已通知区域负责人 · 限时 2 小时复核</span></div>:supervisorActive.reviewStage==='已关闭'?<div className="archive-box">任务已关闭并归档，已计入合规率和抽检样本。</div>:supervisorActive.category==='审查通过'?<button className="primary-button" onClick={()=>archive(supervisorActive)}>督导确认关闭并归档</button>:supervisorActive.category==='需重拍'?<div className="action-grid"><button className="secondary-button" onClick={()=>rejectRephoto(supervisorActive)}>驳回并要求补拍</button><button className="secondary-button" onClick={()=>escalate(supervisorActive)}>高风险升级</button></div>:<div className="action-grid"><button className="primary-button" onClick={()=>archive(supervisorActive)}>复核通过并关闭</button><button className="secondary-button" onClick={()=>rejectRectification(supervisorActive)}>驳回继续整改</button><button className="danger-button" onClick={()=>escalate(supervisorActive)}>高风险升级</button></div>}</>:<p className="photo-tip">切换门店后，可在下方记录卡片中选择待复核任务。</p>}</section>}
 {message&&<p className="notice" role="status">{message}</p>}
 <section className="history-section"><div className="history-title"><p className="section-kicker">本次巡检记录</p><span>{records.length} 张已审核</span></div>{records.length===0?<div className="empty-history">完成首张照片检查后，结果会保留在这里，可左右滑动查看。</div>:<div className="history-groups">{(['审查通过','需重拍','需整改'] as Category[]).map(category=><div className="history-group" key={category}><div className="history-group-title"><Pill value={category}/><span>{categoryRecords(category).length} 条</span></div>{categoryRecords(category).length?<div className="history-row">{categoryRecords(category).map(historyCard)}</div>:<p className="empty-category">暂无记录</p>}</div>)}</div>}</section>
 {active&&<section className="dashboard-card result-card"><div className="result-divider"><span>CHECK RESULT</span></div><div className="card-heading"><div><p className="section-kicker">检查结论</p><h2>{active.finding.item}</h2></div><Pill value={active.finding.status}/></div>{active.beforeImage&&active.afterImage?<div className="compare-images"><figure><img src={active.beforeImage} alt="整改前照片"/><figcaption>整改前</figcaption></figure><figure><img src={active.afterImage} alt="整改后照片"/><figcaption>整改后</figcaption></figure></div>:<img className="evidence-image" src={active.image} alt={`${active.finding.item}的图片证据`}/>}<div className="evidence-caption"><span>图片证据</span><p>{active.finding.evidence}</p></div><dl className="result-grid"><div><dt>对应规则</dt><dd><b>{active.finding.ruleId}</b>{active.finding.ruleText}</dd></div><div><dt>风险等级</dt><dd><Pill value={active.finding.risk}/></dd></div><div><dt>整改建议</dt><dd>{active.finding.recommendation}</dd></div><div><dt>置信度</dt><dd><b>{active.finding.confidence}%</b><span className="confidence"><i style={{width:`${active.finding.confidence}%`}}/></span></dd></div>{active.finding.reason&&<div><dt>无法判断原因</dt><dd>{active.finding.reason}</dd></div>}</dl>{role==='店长'&&active.category!=='审查通过'&&<button className="secondary-button" onClick={rectify} disabled={busy&&replaceId===active.id}>{busy&&replaceId===active.id?'正在检查':active.category==='需重拍'?'重新上传照片':'提交整改后照片'}</button>}</section>}
 <section className="dashboard-card rule-card"><button className="rule-toggle" onClick={()=>setShowRules(!showRules)}><span><i>◎</i> 规则库 v1.0</span><b>{showRules?'收起 −':'查看 +'}</b></button>{showRules&&<div className="rule-list">{rules.map(([id,x])=><article key={id}><b>{id} · {x}</b><p>当前检查仅根据该检查项对应的版本化卫生规则判断。</p></article>)}</div>}</section><footer>系统仅依据已启用规则判定 · 证据不足时输出“无法判断” · 最终结论由督导复核</footer></main>
}
